{% set name = "perl-path-tiny" %}
{% set version = "0.124" %}
{% set sha256 = "fa083144781e46817ec39d21962bbbb0533c201f3baf031d2999a785a2a013fd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Path-Tiny-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Path::Tiny

about:
  home: https://metacpan.org/dist/Path-Tiny
  license: Apache-2.0
  summary: File path utility
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cbrueffer
