{% set name = "perl-path-tiny" %}
{% set version = "0.150" %}
{% set sha256 = "ff20713d1a14d257af9c78209001f40dc177e4b9d1496115cbd8726d577946c7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Path-Tiny-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test -j"${CPU_COUNT}"
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Path::Tiny

about:
  home: "https://metacpan.org/pod/Path::Tiny"
  license: "Apache-2.0"
  summary: "File path utility."
  license_file: LICENSE
  doc_url: "https://metacpan.org/pod/Path::Tiny"

extra:
  recipe-maintainers:
    - cbrueffer
    - conda-forge/perl-packagers
